
/* convert the json generated by csv2geojson to be a line
   from start point to end point.
*/

const data = require('./2013-07-piece.json')

data['features'].forEach( (record) => {
        const endCoords = record.geometry.coordinates;
        record.geometry = {
            type: "LineString",
            coordinates: [
                // start station longitude/latitude
                [
                    record.properties['start station longitude'],
                    record.properties['start station latitude'],
                ],
                // end station longitude/latitude
                endCoords
            ]

        }
        delete record.properties['start station longitude']
        delete record.properties['start station latitude']
    }
)

// print data to stdout
console.log(JSON.stringify(data, null, 4))

