// convert the json generated by csv2geojson to be a line
// from start point to end point.

const jsonfile = require('jsonfile')
const data = require('./2013-07-piece.json')

data['features'].forEach( (record) => {
        const endCoords = record.geometry.coordinates;
        record.geometry = {
            type: "LineString",
            coordinates: [
                // start station longitude/latitude
                [
                    record.properties['start station longitude'],
                    record.properties['start station latitude'],
                ],
                // end station longitude/latitude
                endCoords
            ]

        }
        delete record.properties['start station longitude']
        delete record.properties['start station latitude']
    }
)

// should be
//"40.75323098","-73.97032517","40.73221853","-73.98165557"
// console.log(data.features[0].geometry)
console.log(JSON.stringify(data, null, 4))

